---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.4
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      JINAAI_APIKEY: jina_5d1f8bfbfcb64374b320054c5627291dy0Ph73OTluT40uUOOVb4vn7cAPAr
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-jinaai'
      ENABLE_MODULES: 'text2vec-jinaai, generative-mistral'
      MISTRAL_APIKEY: RVBRn5Sn26ONsd0CbFBjYWJYR9w416kd
      CLUSTER_HOSTNAME: 'node1'
  web:
    build: .
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on:
        - weaviate
    ports:
      - "8000:8000"
    volumes:
        - .:/app

volumes:
  weaviate_data:
...