version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    depends_on:
      - contextionary
      - qna-transformers
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      ENABLE_MODULES: 'text2vec-contextionary,qna-transformers'

  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://10.90.137.169:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    ports:
      - "9999:9999"

  web:
    build: .
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - weaviate
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: '0'

volumes:
  weaviate_data:
